# Generated by Django 2.1.5 on 2019-01-19 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phoneno', models.IntegerField()),
                ('Message', models.TextField()),
                ('contact_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
