# Generated by Django 2.1.5 on 2019-01-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phoneno',
            field=models.CharField(max_length=12),
        ),
    ]
