# Generated by Django 2.1.5 on 2019-01-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
