# Generated by Django 2.1.5 on 2019-01-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190119_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='BlogModel',
        ),
    ]
